export const FETCH_SCHEMA_LIST = "FETCH_SCHEMA_LIST"
export const FETCH_SCHEMA_LIST_SUCCESS = "FETCH_SCHEMA_LIST_SUCCESS"
export const FETCH_SCHEMA_LIST_FAILURE = "FETCH_SCHEMA_LIST_FAILURE"

export const SELECT_SCHEMA = "SELECT_SCHEMA"
export const DESELECT_SCHEMA = "DESELECT_SCHEMA"

export const FETCH_SCHEMA = "FETCH_SCHEMA"
export const FETCH_SCHEMA_SUCCESS = "FETCH_SCHEMA_SUCCESS"
export const FETCH_SCHEMA_FAILURE = "FETCH_SCHEMA_FAILURE"

export const CREATE_DATA_ENTRY = "CREATE_DATA_ENTRY"
export const CREATE_DATA_ENTRY_SUCCESS = "CREATE_DATA_ENTRY_SUCCESS"
export const CREATE_DATA_ENTRY_FAILURE = "CREATE_DATA_ENTRY_FAILURE"

export const CHECK_FOR_DUPLICATE = "CHECK_FOR_DUPLICATE"
export const CHECK_FOR_DUPLICATE_SUCCESS = "CHECK_FOR_DUPLICATE_SUCCESS"
export const CHECK_FOR_DUPLICATE_FAILURE = "CHECK_FOR_DUPLICATE_FAIdLURE"

