
export const LOAD_SCHEMA = 'models/LOAD_SCHEMA'
export const FETCH_SCHEMA_REQUESTED = 'models/FETCH_SCHEMA_REQUESTED'
export const FETCH_SCHEMA_SUCCESS = 'models/FETCH_SCHEMA_SUCCESS'
export const FETCH_SCHEMA_FAILURE = 'models/FETCH_SCHEMA_FAILURE'

export const LOAD_MODEL = 'models/LOAD_MODEL'
export const FETCH_MODEL_REQUESTED = 'models/FETCH_MODEL_REQUESTED'
export const FETCH_MODEL_SUCCESS = 'models/FETCH_MODEL_SUCCESS'
export const FETCH_MODEL_FAILURE = 'models/FETCH_MODEL_FAILURE'